name: random_gen
description: Fast way of generating random strings of text and passwords.
version: 1.0.0
homepage: https://github.com/nathanielxd/random-gen

environment:
  sdk: '>=2.16.2 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
